### PR TITLE
fix `deep_size_of_interned` always returns a fixed value (close #51)

### LINKED ISSUE #51: The result of `deep_size_of_interned` is incorrect
The crate `deepsize` implements `DeepSizeOf` trait for all references. And it only calculates the size of the reference itself, not the size of the pointed-to object.

https://github.com/Aeledfyr/deepsize/blob/5deebe687695610e6038dc70753defbe7634d549/src/lib.rs#L421-L444

Therefore, we must manually dereference before calling `deep_size_of`.

https://github.com/droundy/internment/blob/1eb3a8046b04694eba797109e61a444e02ba4116/src/intern.rs#L79

### PR DESCRIPTION
**Pull request by gmryuuko**
fix #51 
And fix a compile error when `arena` and `deepsize` are enabled at the same time.

### CODE REVIEW

File: src/arena.rs [hunk 1]
```diff
@@ -2,6 +2,7 @@
 use crate::boxedset::HashSet;
 use std::borrow::Borrow;
 use std::hash::{Hash, Hasher};
+use std::ops::Deref;
```
Comment (droundy) [inline src/arena.rs:5]: I wouldn't have thought that this `use` would be required.

File: src/intern.rs [hunk 2]
```diff
@@ -506,6 +518,112 @@ mod intern_tests {
             h.join().unwrap()
         }
     }
+
+    #[cfg(feature = "deepsize")]
+    #[test]
+    fn test_deep_size() {
+        let string1 = String::from("abcdefghijklmnopqrstuvwxyz");
+        let string2 = String::from("abcdefghijklmnopqrstuvwxyz");
+        let string3 = String::from("abcdefghijklmnopqrstuvwxyz");
```
Comment (droundy) [inline src/intern.rs:527]: Might be a little more clear with clone
```suggestion
        let string2 = string1.clone();
        let string3 = string1.clone();
```

File: src/intern.rs [hunk 3]
```diff
@@ -506,6 +518,112 @@ mod intern_tests {
...
+        assert_eq!(
+            interned_size,
+            string_size + object_size + set_size + pointers_in_set_size
+        );
+
+        println!("string_size: {}", string_size);
+        println!("object_size: {}", object_size);
+        println!("set_size: {}", set_size);
+        println!("pointers_in_set_size: {}", pointers_in_set_size);
+        println!("interned_size: {}", interned_size);
```
Comment (droundy) [inline src/intern.rs:625]: I'd prefer to put the printlns before the assertion, so if it fails it's easier to see what went wrong.
```suggestion
        println!("string_size: {}", string_size);
        println!("object_size: {}", object_size);
        println!("set_size: {}", set_size);
        println!("pointers_in_set_size: {}", pointers_in_set_size);
        println!("interned_size: {}", interned_size);

        assert_eq!(
            interned_size,
            string_size + object_size + set_size + pointers_in_set_size
        );
```

**Review by droundy — APPROVED** [review]
I left a few comments where I think it might be approved, but assuming tests pass I'll probably just merge as is.  Thanks so much for this careful and thoughtful contribution!

**Comment by gmryuuko** [comment]
> I left a few comments where I think it might be approved, but assuming tests pass I'll probably just merge as is. Thanks so much for this careful and thoughtful contribution!

fixed

**Comment by droundy** [comment]
> > I left a few comments where I think it might be approved, but assuming tests pass I'll probably just merge as is. Thanks so much for this careful and thoughtful contribution!
> 
> fixed

Wow, that was fast!
